In [11]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import learning_curve, validation_curve
%matplotlib
import matplotlib.pyplot as plt
import numpy as np

Using matplotlib backend: Qt5Agg


In [12]:
# 添加列名
header_row = ['age','sex','cp','trestbps','chol','fbs',\
                'restecg','thalach','exang','oldpeak','slope','ca','thal','target']
 
# 载入数据
heart = pd.read_csv('processed.cleveland.data.csv',names=header_row)

In [13]:
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
5     56    1   2       120   236    0        0      178      0      0.8   
6     62    0   4       140   268    0        2      160      0      3.6   
7     57    0   4       120   354    0        0      163      1      0.6   
8     63    1   4       130   254    0        2      147      0      1.4   
9     53    1   4       140   203    1        2      155      1      3.1   
10    57    1   4       140   192    0        0      148      0      0.4   
11    56    0   2       140   294    0        2      153      0      1.3   
12    56    1   3       130   256    1        2      142      1      0.6   
13    44    1   2       120   263    0        0      173      0      0.0   
14    52    1   3       172   199    1        0      162      0      0.5   
15    57    1   3       150   168    0        0      174      0      1.6   
16    48    1   2       110   229    0        0      168      0      1.0   
17    54    1   4       140   239    0        0      160      0      1.2   
18    48    0   3       130   275    0        0      139      0      0.2   
19    49    1   2       130   266    0        0      171      0      0.6   
20    64    1   1       110   211    0        2      144      1      1.8   
21    58    0   1       150   283    1        2      162      0      1.0   
22    58    1   2       120   284    0        2      160      0      1.8   
23    58    1   3       132   224    0        2      173      0      3.2   
24    60    1   4       130   206    0        2      132      1      2.4   
25    50    0   3       120   219    0        0      158      0      1.6   
26    58    0   3       120   340    0        0      172      0      0.0   
27    66    0   1       150   226    0        0      114      0      2.6   
28    43    1   4       150   247    0        0      171      0      1.5   
29    40    1   4       110   167    0        2      114      1      2.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
267   66    1   4       160   228    0        2      138      0      2.3   
268   46    1   4       140   311    0        0      120      1      1.8   
269   71    0   4       112   149    0        0      125      0      1.6   
270   59    1   1       134   204    0        0      162      0      0.8   
271   64    1   1       170   227    0        2      155      0      0.6   
272   66    0   3       146   278    0        2      152      0      0.0   
273   39    0   3       138   220    0        0      152      0      0.0   
274   57    1   2       154   232    0        2      164      0      0.0   
275   58    0   4       130   197    0        0      131      0      0.6   
276   57    1   4       110   335    0        0      143      1      3.0   
277   47    1   3       130   253    0        0      179      0      0.0   
278   55    0   4       128   205    0        1      130      1      2.0   
279   35    1   2       122   192    0        0      174      0      0.0   
280   61    1   4       148   203    0        0      161      0      0.0   
281   58    1   4       114   318    0        1      140      0      4.4   
282   58    0   4       170   225    1        2      146      1      2.8   
283   56    1   2       130   221    0        2      163      0      0.0   
284   56    1   2       120   240    0        0      169      0      0.0   
285   67    1   3       152   212    0        2      150      0      0.8   
286   55    0   2       132   342    0        0      166      0      1.2   
287   44    1   4       120   169    0        0      

In [17]:
x=heart[['age','sex','cp','trestbps','chol','fbs',\
                'restecg','thalach','exang','oldpeak','slope','ca','thal']]
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
5     56    1   2       120   236    0        0      178      0      0.8   
6     62    0   4       140   268    0        2      160      0      3.6   
7     57    0   4       120   354    0        0      163      1      0.6   
8     63    1   4       130   254    0        2      147      0      1.4   
9     53    1   4       140   203    1        2      155      1      3.1   
10    57    1   4       140   192    0        0      148      0      0.4   
11    56    0   2       140   294    0        2      153      0      1.3   
12    56    1   3       130   256    1        2      142      1      0.6   
13    44    1   2       120   263    0        0      173      0      0.0   
14    52    1   3       172   199    1        0      162      0      0.5   
15    57    1   3       150   168    0        0      174      0      1.6   
16    48    1   2       110   229    0        0      168      0      1.0   
17    54    1   4       140   239    0        0      160      0      1.2   
18    48    0   3       130   275    0        0      139      0      0.2   
19    49    1   2       130   266    0        0      171      0      0.6   
20    64    1   1       110   211    0        2      144      1      1.8   
21    58    0   1       150   283    1        2      162      0      1.0   
22    58    1   2       120   284    0        2      160      0      1.8   
23    58    1   3       132   224    0        2      173      0      3.2   
24    60    1   4       130   206    0        2      132      1      2.4   
25    50    0   3       120   219    0        0      158      0      1.6   
26    58    0   3       120   340    0        0      172      0      0.0   
27    66    0   1       150   226    0        0      114      0      2.6   
28    43    1   4       150   247    0        0      171      0      1.5   
29    40    1   4       110   167    0        2      114      1      2.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
267   66    1   4       160   228    0        2      138      0      2.3   
268   46    1   4       140   311    0        0      120      1      1.8   
269   71    0   4       112   149    0        0      125      0      1.6   
270   59    1   1       134   204    0        0      162      0      0.8   
271   64    1   1       170   227    0        2      155      0      0.6   
272   66    0   3       146   278    0        2      152      0      0.0   
273   39    0   3       138   220    0        0      152      0      0.0   
274   57    1   2       154   232    0        2      164      0      0.0   
275   58    0   4       130   197    0        0      131      0      0.6   
276   57    1   4       110   335    0        0      143      1      3.0   
277   47    1   3       130   253    0        0      179      0      0.0   
278   55    0   4       128   205    0        1      130      1      2.0   
279   35    1   2       122   192    0        0      174      0      0.0   
280   61    1   4       148   203    0        0      161      0      0.0   
281   58    1   4       114   318    0        1      140      0      4.4   
282   58    0   4       170   225    1        2      146      1      2.8   
283   56    1   2       130   221    0        2      163      0      0.0   
284   56    1   2       120   240    0        0      169      0      0.0   
285   67    1   3       152   212    0        2      150      0      0.8   
286   55    0   2       132   342    0        0      166      0      1.2   
287   44    1   4       120   169    0        0      

In [29]:

#心脏病（0=否，1=是）
heart["target"] = np.where(heart["target"] != 0, 1, 0)
y=heart.target

In [30]:
y

0      0
1      1
2      1
3      0
4      0
5      0
6      1
7      0
8      1
9      1
10     0
11     0
12     1
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     1
24     1
25     0
26     0
27     0
28     0
29     1
      ..
267    0
268    1
269    0
270    1
271    0
272    0
273    0
274    1
275    0
276    1
277    0
278    1
279    0
280    1
281    1
282    1
283    0
284    0
285    1
286    0
287    1
288    1
289    1
290    0
291    1
292    1
293    1
294    1
295    1
296    1
Name: target, Length: 297, dtype: int32

In [31]:
#分割数据集到训练集和数据集
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
#进行处理（特征工程）one hot 编码
dict=DictVectorizer(sparse=False)
x_train=dict.fit_transform(x_train.to_dict(orient="records"))
print(dict.get_feature_names())
x_test=dict.transform(x_test.to_dict(orient="records"))
print(x_train)


['age', 'ca', 'chol', 'cp', 'exang', 'fbs', 'oldpeak', 'restecg', 'sex', 'slope', 'thal', 'thalach', 'trestbps']
[[ 55.   0. 250. ...   3. 161. 135.]
 [ 50.   0. 254. ...   3. 159. 110.]
 [ 41.   0. 172. ...   7. 158. 110.]
 ...
 [ 65.   0. 177. ...   7. 140. 120.]
 [ 57.   1. 236. ...   3. 174. 130.]
 [ 59.   1. 177. ...   7. 162. 140.]]


In [32]:
#用决策树进行预测
dec=DecisionTreeClassifier(max_depth=6,min_samples_leaf=5,min_samples_split=2)
dec.fit(x_train,y_train)

#####20201023
train_size, train_scores, test_scores = learning_curve(dec, x_train, y_train, cv=10, scoring='accuracy',#10折交叉验证
                                                       train_sizes = np.linspace(0.1,1.0,10))#5次的训练数量占比
mean_train = np.mean(train_scores,1)  #(5,)
# 得到得分范围的上下界
upper_train = np.clip(mean_train + np.std(train_scores,1),0,1) 
lower_train = np.clip(mean_train - np.std(train_scores,1),0,1)
    
mean_test = np.mean(test_scores,1)
# 得到得分范围的上下界
upper_test = np.clip(mean_test + np.std(test_scores,1),0,1) 
lower_test = np.clip(mean_test - np.std(test_scores,1),0,1)



plt.figure('Fig1')
plt.plot(train_size,mean_train,'ro-',label='train score')
plt.plot(train_size,mean_test,'go-',label='test score')
##填充上下界的范围
plt.fill_between(train_size,upper_train,lower_train,alpha=0.2,#alpha：覆盖区域的透明度[0,1],其值越大，表示越不透明 
         color='r')                   
plt.fill_between(train_size,upper_test,lower_test,alpha=0.2,#alpha：覆盖区域的透明度[0,1],其值越大，表示越不透明 
         color='g')  
plt.grid()
plt.xlabel('train size')
plt.ylabel('score')
plt.legend(loc='lower right')
plt.title('Decision Trees')
plt.savefig('train number-size.png')
plt.show()


######20201023
#预测准确率
print("预测的准确率：",dec.score(x_test,y_test))
#['一卡通消费', '上网情况得分', '图书馆得分', '心理健康调查问卷得分', '成绩得分', '社交得分', '网络空间状态得分', '获奖情况得分']
#导出决策树的结构
export_graphviz(dec,out_file='tree.dot',feature_names=['age','sex','cp','trestbps','chol','fbs',\
                'restecg','thalach','exang','oldpeak','slope','ca','thal'],class_names=['0','1','2','3','4'],filled=True, rounded=True,
                         special_characters=True)


预测的准确率： 0.7666666666666667


In [33]:
#用随机森林进行预测(超参数调优)
rf=RandomForestClassifier()

param={"n_estimators":[120,200,300,500,800,1200],"max_depth":[5,8,15,25,30]}
#网格搜索与交叉验证
gc=GridSearchCV(rf,param_grid=param,cv=2)
gc.fit(x_train,y_train)

print("准确率:",gc.score(x_test,y_test))
print("选择的参数模型：",gc.best_params_)



准确率: 0.8
选择的参数模型： {'max_depth': 8, 'n_estimators': 300}


In [34]:
import os
os.environ["PATH"]+= os.pathsep + 'E:/Graphviz/bin'
from subprocess import call
call(['dot', '-Tpng','tree.dot', '-o', 'tree.png', '-Gdpi=600'])
 
# 在jupyter notebook中查看决策树图像
from IPython.display import Image
Image(filename ='tree.png')


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [26]:
import codecs
txt_dir = 'tree.dot'   
txt_dir_utf8 = 'tree_utf8.dot'  

with codecs.open(txt_dir, 'r',encoding='utf-8') as f, codecs.open(txt_dir_utf8, 'w', encoding='utf-8') as wf:
    for line in f:
        lines = line.strip().split('\t')
        print(lines)
        if 'label' in lines[0]:
            newline = lines[0].replace('\n', '').replace(' ', '')
        else:
            newline = lines[0].replace('\n','').replace('helvetica', ' "Microsoft YaHei" ')
        wf.write(newline + '\t')


['digraph Tree {']
['node [shape=box, style="filled, rounded", color="black", fontname=helvetica] ;']
['edge [fontname=helvetica] ;']
['0 [label=<trestbps &le; 3.5<br/>gini = 0.632<br/>samples = 207<br/>value = [115, 36, 26, 23, 7]<br/>class = 0>, fillcolor="#f3c5a4"] ;']
['1 [label=<restecg &le; 1.95<br/>gini = 0.317<br/>samples = 104<br/>value = [85, 12, 4, 2, 1]<br/>class = 0>, fillcolor="#ea9b62"] ;']
['0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;']
['2 [label=<slope &le; 6.5<br/>gini = 0.223<br/>samples = 96<br/>value = [84, 10, 1, 1, 0]<br/>class = 0>, fillcolor="#e99355"] ;']
['1 -> 2 ;']
['3 [label=<age &le; 57.5<br/>gini = 0.128<br/>samples = 73<br/>value = [68, 5, 0, 0, 0]<br/>class = 0>, fillcolor="#e78a48"] ;']
['2 -> 3 ;']
['4 [label=<thal &le; 109.0<br/>gini = 0.038<br/>samples = 52<br/>value = [51, 1, 0, 0, 0]<br/>class = 0>, fillcolor="#e6833d"] ;']
['3 -> 4 ;']
['5 [label=<gini = 0.32<br/>samples = 5<br/>value = [4, 1, 0, 0, 0]<br/>class = 0>, fillcolo

In [35]:
import pydot
(graph, ) = pydot.graph_from_dot_file('tree.dot',encoding="utf-8")
graph.write_png('tree.png')

FileNotFoundError: [WinError 2] "dot" not found in path.